language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy"
env:
  - DJANGO=1.4.5
  - DJANGO=1.3.7
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py -q install
script:
  - python setup.py test

