language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.6.1
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=1.6.1
    - python: "3.5"
      env: DJANGO=1.6.1
    - python: "3.5"
      env: DJANGO=1.7
    - python: "3.5"
      env: DJANGO=1.8
  include:
    - python: "3.2"
      env: DJANGO=1.5
    - python: "3.3"
      env: DJANGO=1.5
    - python: "3.2"
      env: DJANGO=1.6.1
    - python: "3.3"
      env: DJANGO=1.6.1
    - python: "3.2"
      env: DJANGO=1.7
    - python: "3.3"
      env: DJANGO=1.7
install:
  - pip install -q Django==$DJANGO 
  - python setup.py -q install
script:
  - python setup.py test

