language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy"
env:
  - DJANGO=1.4.5
  - DJANGO=1.3.7
  - DJANGO=1.5
  - DJANGO=1.6.1
matrix:
  exclude:
    - python: "2.5"
      env: DJANGO=1.5
    - python: "2.5"
      env: DJANGO=1.6.1
      python: "2.6"
      env: DJANGO=1.6.1
  include:
    - python: "3.2"
      env: DJANGO=1.5
    - python: "3.3"
      env: DJANGO=1.5
    - python: "3.3"
      env: DJANGO=1.6.1
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py -q install
script:
  - python setup.py test

